### ISSUE TITLE
Keeps resetting settings to default

### ISSUE THREAD

**Issue by vemilyus** [mallowigi/material-theme-jetbrains-eap#125]
I can do whatever changes to the settings I want, as soon as I restart IntelliJ they are reset to default.

Material Theme UI EAP Version: 0.9.0

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.29, built on August 8, 2017
Licensed to ***
Subscription is active until ***
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by stef-k** [comment]
I can confirm this on Phpstorm

PhpStorm 2017.2.2 EAP
Build #PS-172.3757.34, built on August 9, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-30-generic

**Comment by roboslone** [comment]
Same here, that's really annoying, please fix that.

PyCharm 2017.2.1
Build #PY-172.3544.46, built on August 9, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
I am away from keyboard at the moment. I don't know what's happening but I will get to it as soon as I go home. In the meantime if it doesn't work please download 8.1

**Comment by roboslone** [comment]
Any progress here?

**Comment by roboslone** [comment]
@mallowigi, sorry, didn't see that another thread.

It seems, there's no `material-theme.xml` on my machine:
```
Material\ Theme
└── lib
    ├── javassist-3.21.0-GA.jar
    ├── material-theme-jetbrains.jar
    └── xstream-1.4.8.jar

1 directory, 3 files
```

Should I create it? And if so, could you provide default configuration?

**Comment by mallowigi** [comment]
It should be in /Library/Preferences/.IntelliJIdea2017.X/config in Mac or C:/Users/user/.IntellijIdea2017.X/config in Windows (replace IntelliJ by PhpStorm or Webstorm if you're using something else)

--
Elior

**Comment by roboslone** [comment]
It's not there. Perhaps that's the problem?

**Comment by roboslone** [comment]
Oh, I found this: `~/Library/Preferences/PyCharm2017.2/options/material_theme.xml`.
I'll try to patch it.

**Comment by roboslone** [comment]
Nope, didn't work. I think plugin stores current options there, but doesn't load them on init.

**Comment by roboslone** [comment]
I think I know what the problem is.
Plugin reads `~/Library/Preferences/PyCharm2017.2/options/material_theme.xml` on boot, but it doesn't write `isUpperCaseTabs` option there. Other options (background wallpaper, accent color, themed scrollbars) seem to be okay.
So I've added `isUpperCaseTabs` option manually to `material_theme.xml` and on the next boot `material_theme.xml` was overridden, and now there's only one option there - `defaultBackground`.

I believe adding `isUpperCaseTabs` to `material_theme.xml` breaks it. So a temporarily solution is to run IDE with upper case tabs turned on.

**Comment by roboslone** [comment]
Here's a stacktrace:
```
2017-08-14 16:18:26,703 [  34654]  ERROR - rationStore.ComponentStoreImpl - Cannot init MaterialThemeConfig component state 
com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.chrisrm.idea.MTConfig
	at com.intellij.configurationStore.XmlSerializer.deserialize(xmlSerializer.kt:85)
	at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:40)
	at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:42)
	at com.intellij.configurationStore.StateGetter.getState(StorageBaseEx.kt:44)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:316)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:291)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at com.chrisrm.idea.MTConfig.getInstance(MTConfig.java:113)
	at com.chrisrm.idea.MTLafComponent.installMaterialComponents(MTLafComponent.java:351)
	at com.chrisrm.idea.MTLafComponent.initComponent(MTLafComponent.java:79)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:475)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:482)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:420)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: No argument provided for a required parameter: parameter #0 arg0 of fun <init>(kotlin.Float, kotlin.Float, kotlin.Float, kotlin.Float): java.awt.Color
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(KCallableImpl.kt:137)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at com.intellij.configurationStore.KotlinAwareBeanBinding.a(xmlSerializer.kt:217)
	at com.intellij.configurationStore.KotlinAwareBeanBinding.a(xmlSerializer.kt:204)
	at com.intellij.configurationStore.KotlinAwareBeanBinding.deserialize(xmlSerializer.kt:183)
	at com.intellij.util.xmlb.NotNullDeserializeBinding.deserializeUnsafe(NotNullDeserializeBinding.java:32)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:58)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:66)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:234)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:188)
	at com.intellij.configurationStore.KotlinAwareBeanBinding.deserialize(xmlSerializer.kt:184)
	at com.intellij.configurationStore.XmlSerializer.deserialize(xmlSerializer.kt:79)
	... 48 more
2017-08-14 16:18:26,705 [  34656]  ERROR - rationStore.ComponentStoreImpl - PyCharm 2017.2.1  Build #PY-172.3544.46 
2017-08-14 16:18:26,705 [  34656]  ERROR - rationStore.ComponentStoreImpl - JDK: 1.8.0_152-release 
2017-08-14 16:18:26,705 [  34656]  ERROR - rationStore.ComponentStoreImpl - VM: OpenJDK 64-Bit Server VM 
2017-08-14 16:18:26,705 [  34656]  ERROR - rationStore.ComponentStoreImpl - Vendor: JetBrains s.r.o 
2017-08-14 16:18:26,706 [  34657]  ERROR - rationStore.ComponentStoreImpl - OS: Mac OS X 
```

**Comment by mallowigi** [comment]
Ok I've fixed the issue (damn it autocomplete) but I can't release the version for now. Those who have the project installed can take the latest changes and run the gradle build command to generate the plugin and load it manually. If someone is kind enough to add do so and add the build to the source control and send me a pull request, I'll appreciate.

**Comment by ForsakenHarmony** [comment]
why did you even add this feature? bold upper-casing tabs doesn't make a lot of sense to me

**Comment by mallowigi** [comment]
I wanted to make proper MDTabs, cause all MD designs share this feature. But it's not the result I expected, I think opened files are not supposed to be styled as such.

I will try to play with it a little and if there's nothing good coming to it, I'll remove it.

--
Elior

**Comment by mallowigi** [comment]
Finally got access to my computer. 

I didn't remove the feature in the end, just replaced uppercase to "spaced uppercase" and set it to false by default. And fixed the issue with the settings not saved.

Please tell me if there are other issues.

**Comment by ForsakenHarmony** [comment]
just tried to enable it to see what it looks like now and it seems to throw an error

```
com.intellij.ide.ui.UISettings.getHdeKnownExtensionInTabs()Z
java.lang.NoSuchMethodError: com.intellij.ide.ui.UISettings.getHdeKnownExtensionInTabs()Z
	at com.chrisrm.idea.tabs.MTEditorUpperTabs.getEditorTabTitle(MTEditorUpperTabs.java:42)
```

**Comment by mallowigi** [comment]
Which ide?

**Comment by ForsakenHarmony** [comment]
that's webstorm, also all my settings seem to be messed up now

**Comment by detwetter** [comment]
My settings are not being retained on a restart still.

**Comment by ForsakenHarmony** [comment]
it reset it once for me, but seems to work now
