### ISSUE TITLE
Plugin fails to initialize

### ISSUE THREAD

**Issue by tadfisher** [mallowigi/material-theme-jetbrains-eap#159]
On launch, the Material Theme EAP plugin is disabled due to an exception:

```
Plugin 'com.chrisrm.idea.MaterialThemeUIFork' failed to initialize and will be disabled.  Please restart Android Studio.

java.util.ConcurrentModificationException
    at java.util.Hashtable$Enumerator.next(Hashtable.java:1378)
    at com.intellij.ide.ui.laf.LafManagerImpl.patchHiDPI(LafManagerImpl.java:553)
    at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:513)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:367)
    at com.chrisrm.idea.MTThemeManager.activate(MTThemeManager.java:313)
    at com.chrisrm.idea.schemes.MTThemesComponent.activateTheme(MTThemesComponent.java:49)
    at com.chrisrm.idea.schemes.MTThemesComponent.initComponent(MTThemesComponent.java:42)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Environment

```
Android Studio 3.0 Beta 2
Build #AI-171.4263559, built on August 10, 2017
JRE: 1.8.0_152-release-970-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-rc6-mainline
```

Plugin version: 0.9.4

**Comment by mallowigi** [comment]
Android Studio hasn't been updated for a while, and is not compatible with the Material Theme EAP.

Try with the Material Theme, if i remember correctly it should work.

**Comment by tadfisher** [comment]
This is the Beta version, which is based on 2017.2.

**Comment by mallowigi** [comment]
Where can you find the beta?

**Comment by mallowigi** [comment]
ok found it. I will work on it

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/29887401-f8132e66-8dc5-11e7-8b32-00932a6fc81d.png)

Works fine to me
