### ISSUE TITLE
NullPointerException in MTWallpaperComponent

### ISSUE THREAD

**Issue by phisch** [mallowigi/material-theme-jetbrains-eap#162]
### Summary
`MTWallpaperComponent` seems to be broken after https://github.com/mallowigi/material-theme-jetbrains-eap/commit/46b572e5827c8fbde0377b3292cd4d2b124677e5

### Expected behavior
PhpStorm starts as expected.

### Actual behavior
PhpStorm prints error message and disables the Plugin.

```
Plugin 'com.chrisrm.idea.MaterialThemeUIFork' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NullPointerException
    at com.chrisrm.idea.wallpaper.MTWallpaperComponent.updateDefaultBackground(MTWallpaperComponent.java:118)
    at com.chrisrm.idea.wallpaper.MTWallpaperComponent.reloadWallpaper(MTWallpaperComponent.java:135)
    at com.chrisrm.idea.wallpaper.MTWallpaperComponent.initComponent(MTWallpaperComponent.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:474)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:481)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:419)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to reproduce (if needed)

1. install the latest version (10.0.1 or 10.0.2 - should affect both)
2. restart PhpStorm

### Environment
Not relevant for this bug.

**Comment by mallowigi** [comment]
should be fixed asap

**Comment by phisch** [comment]
https://github.com/mallowigi/material-theme-jetbrains-eap/commit/4a89081f7f3f97306e67acdaaf942d35ed1ddc99 fixed the issue. Thanks @mallowigi 

By the way, i tried fixing it myself, but realised that a bunch of the tests are failing and the code style definitions are not satisfied either, which both makes the gradle build fail. Am i doing something wrong, or do you just skip those for your builds?

**Comment by mallowigi** [comment]
I don't run the tests. They were written ages ago and are not updated to the new Jetbrains API 

What did you run? Just run runIde gradle task

**Comment by mallowigi** [comment]
Also for checkstyle, I don't understand why the gradle task fails while the ide's pass (except some methods that I'm not bothering fixing)

**Comment by phisch** [comment]
```
[phisch@tower:~/code]$ git clone git@github.com:mallowigi/material-theme-jetbrains-eap.git
Cloning into 'material-theme-jetbrains-eap'...
remote: Counting objects: 14571, done.
remote: Compressing objects: 100% (399/399), done.
remote: Total 14571 (delta 404), reused 796 (delta 340), pack-reused 13673
Receiving objects: 100% (14571/14571), 86.98 MiB | 13.79 MiB/s, done.
Resolving deltas: 100% (4821/4821), done.
[phisch@tower:~/code]$ cd material-theme-jetbrains-eap                                                                                      (09-02 21:02)
[phisch@tower:code/material-theme-jetbrains-eap]$ idea .
```

JetBrains IDEA opens and asks me to select a gradle jvm, i select `1.8` and confirm.
After opening the gradle panel, it gives me the error:

```
gradlError:(84, 0) Could not get unknown property 'ideaVersion' for object of type org.jetbrains.intellij.IntelliJPluginExtension.
<a href="openFile:/home/phisch/code/material-theme-jetbrains-eap/build.gradle">Open File</a>
```

So i create a `gradle.properties` file:

```
ideaVersion = LATEST-EAP-SNAPSHOT
idePath = ''
publishUsername = ''
publishPassword = ''
```

And now i can run the gradle tasks inside the IDE, but `checkstyleMain` fails. It also fails if i run `gradle build` in the terminal.

```bash
[phisch@tower:code/material-theme-jetbrains-eap][1]$ gradle build                                                                                                                                                                                                   (09-02 21:15)
Cannot find alternate SDK path: ''. Default IDEA will be used : /home/phisch/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/LATEST-EAP-SNAPSHOT/8309f120f371788d5eac8a9b2161605f06fe1431/ideaIU-LATEST-EAP-SNAPSHOT
:compileJava UP-TO-DATE
:patchPluginXml UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:instrumentCode UP-TO-DATE
:postInstrumentCode
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
:jar UP-TO-DATE
:prepareSandbox UP-TO-DATE
:buildPlugin UP-TO-DATE
:assemble UP-TO-DATE
:checkstyleMain[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:48:17: Variable 'treeSelectionColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:49:17: Variable 'buttonHighlightColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:50:17: Variable 'highlightColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:51:17: Variable 'secondBorderColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:52:17: Variable 'tableSelectedColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:53:17: Variable 'contrastColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:54:17: Variable 'disabledColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:55:17: Variable 'secondaryBackgroundColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:56:17: Variable 'caretColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:57:17: Variable 'inactiveColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:58:17: Variable 'selectionForegroundColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:59:17: Variable 'selectionBackgroundColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:60:17: Variable 'textColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:61:17: Variable 'foregroundColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTCustomThemeConfig.java:62:17: Variable 'backgroundColor' must be private and have accessor methods. [VisibilityModifier]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTLaf.java:47:3: Method 'getPrefix' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTLaf.java:58:3: Method 'parseValue' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTLightLaf.java:45:3: Method 'getPrefix' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTLightLaf.java:56:3: Method 'parseValue' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:64:3: Method 'getDisabled' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:75:7: '}' at column 7 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:137:3: Method 'getTheme' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:141:3: Method 'getTreeSelectionResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:147:3: Method 'getButtonHighlightResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:154:3: Method 'getHighlightResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:163:3: Method 'getSecondBorderResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:171:3: Method 'getTableSelectedResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:183:3: Method 'getContrastResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:190:3: Method 'getDisabledResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:200:3: Method 'getSecondaryBackgroundResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:207:3: Method 'getCaretResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:213:3: Method 'getInactiveResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:225:3: Method 'getSelectionForegroundResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:241:3: Method 'getSelectionBackgroundResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:253:3: Method 'getTextResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:265:3: Method 'getBackgroundResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:325:3: Method 'getForegroundResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:353:3: Method 'getTreeIndent' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:360:3: Method 'getBackgroundColor' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:372:3: Method 'getBorderColor' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:380:3: Method 'getBorderThickness' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:387:3: Method 'getContrastColor' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/MTTheme.java:416:3: Method 'toString' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/actions/themes/MTAbstractThemeAction.java:40:3: Method 'update' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/actions/themes/MTOneDarkThemeAction.java:35:3: Method 'isSelected' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/actions/themes/MTOneDarkThemeAction.java:40:3: Method 'setSelected' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/MTConfigurableBase.java:95:3: Method 'createComponent' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/MTConfigurableBase.java:108:3: Method 'apply' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/MTConfigurableBase.java:117:3: Method 'reset' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/MTConfigurableBase.java:126:3: Method 'disposeUIResources' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/ui/MTCustomThemeForm.java:195:3: Method length is 282 lines (max allowed is 150). [MethodLength]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/ui/MTCustomThemeForm.java:234:5: Avoid nested blocks. [AvoidNestedBlocks]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/config/ui/MTCustomThemeForm.java:250:7: Avoid nested blocks. [AvoidNestedBlocks]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/schemes/MTFileColors.java:2: Line does not match expected header line of ' * The MIT License \(MIT\)'. [RegexpHeader]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/schemes/MTFileColors.java:27:7: '(' should be on the previous line. [MethodParamPad]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/themes/LafTheme.java:2: Line does not match expected header line of ' * The MIT License \(MIT\)'. [RegexpHeader]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/tree/MTProjectViewNodeDecorator.java:77:5: '}' at column 5 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/tree/MTProjectViewNodeDecorator.java:117:72: Must have at least one statement. [EmptyBlock]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTButtonPainter.java:49:3: Method 'getBorderInsets' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTButtonUI.java:72:3: Method 'installDefaults' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTButtonUI.java:87:3: Method 'createButtonListener' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTButtonUI.java:218:3: Method 'paintDecorations' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTButtonUI.java:273:3: Method 'paintText' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTCheckBoxUI.java:166:30: Parameter g should be final. [FinalParameters]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTCheckBoxUI.java:166:44: Parameter w should be final. [FinalParameters]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTCheckBoxUI.java:166:51: Parameter h should be final. [FinalParameters]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTMenuItemUIBase.java:140:3: Method 'paintCheckIcon' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:46: Line is longer than 140 characters (found 142). [LineLength]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:52:21: '(' is followed by whitespace. [ParenPad]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:79:9: '}' at column 9 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:102:36: Parameter g should be final. [FinalParameters]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:102:48: Parameter tr should be final. [FinalParameters]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:120:79: Parameter checkProperty should be final. [FinalParameters]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/ui/MTTreeUI.java:171:7: '}' at column 7 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/utils/IconReplacer.java:57:11: '}' at column 11 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/utils/IconReplacer.java:64:11: '}' at column 11 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/utils/IconReplacer.java:69:9: '}' at column 9 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
[ant:checkstyle] [ERROR] /home/phisch/code/material-theme-jetbrains-eap/src/main/java/com/chrisrm/idea/utils/IconReplacer.java:112:5: '}' at column 5 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else or try/catch/finally). [RightCurly]
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///home/phisch/code/material-theme-jetbrains-eap/build/reports/checkstyle/main.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
9 actionable tasks: 2 executed, 7 up-to-date
```

If no one cares/runs the tests, throw them away, especially if they are outdated and don't test anything important. And for the checkstyle, either comply to the standard defined inside the project, or throw the checkstyle away. Defining a guideline and breaking it isn't worth it. @mallowigi

**Comment by mallowigi** [comment]
I'm running only the tasks defined by the gradle-intellij-plugin, e.g runIde, buildPlugin and publishPlugin. These don't run the tests.

As for the Checkstyle you;re right, I should fix these issues.
