### ISSUE TITLE
Latest version throws exception

### ISSUE THREAD

**Issue by ssmithstone** [mallowigi/material-theme-jetbrains-eap#182]
null
java.lang.NullPointerException
	at com.chrisrm.idea.ui.MTSliderUI.installUI(MTSliderUI.java:44)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JSlider.setUI(JSlider.java:313)
	at javax.swing.JSlider.updateUI(JSlider.java:323)
	at javax.swing.JSlider.<init>(JSlider.java:275)
	at com.intellij.codeInsight.daemon.impl.HectorComponent.<init>(HectorComponent.java:99)
	at com.intellij.openapi.wm.impl.status.TogglePopupHintsPanel.a(TogglePopupHintsPanel.java:88)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl$IconPresentationWrapper$1.mousePressed(IdeStatusBarImpl.java:757)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Just updated to the latest version of the plugin and running on the 2017.2.4

**Comment by mallowigi** [comment]
ide ? os?

**Comment by rudedogg** [comment]
Seeing the same thing, using the One Dark theme. All other settings are Default.

Can trigger the error by going to `Preferences`->`Appearance & Behavior`->`Appearance`.

I tried switching to the default theme and the same thing happens. Running AppCode EAP and macOS 10.13.

**Comment by mallowigi** [comment]
should be fixed in latest update (0.12.0.3)
