### ISSUE TITLE
Error when set background image

### ISSUE THREAD

**Issue by kotakbulet** [mallowigi/material-theme-jetbrains-eap#183]
```
java.lang.NullPointerException
	at com.chrisrm.idea.ui.MTSliderUI.installUI(MTSliderUI.java:44)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JSlider.setUI(JSlider.java:313)
	at javax.swing.JSlider.updateUI(JSlider.java:323)
	at javax.swing.JSlider.<init>(JSlider.java:275)
	at javax.swing.JSlider.<init>(JSlider.java:182)
	at org.intellij.images.editor.actions.SetBackgroundImageDialog.m(SetBackgroundImageDialog.java)
	at org.intellij.images.editor.actions.SetBackgroundImageDialog.<init>(SetBackgroundImageDialog.java:79)
	at org.intellij.images.editor.actions.SetBackgroundImageAction.actionPerformed(SetBackgroundImageAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.ide.actions.GotoActionAction.a(GotoActionAction.java:337)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:270)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

----------------------------------------------------------------- 

### Environment

PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017

JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13

_Thanks in advance!_

**Comment by mallowigi** [comment]
should be fixed in last update (0.12.0.3)
