### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by IGassmann** [mallowigi/material-theme-jetbrains-eap#41]
Error happen when I open the tool on side "Project View".

```
null
java.lang.NullPointerException
	at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:47)
	at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by adaroobi** [comment]
The same here. Addition append to @IGassmann stacktrace:
```
java.lang.NullPointerException		
		at com.chrisrm.idea.icons.Associations.findAssociationForFile(Associations.java:47)		
		at com.chrisrm.idea.icons.MTFileIconProvider.getIcon(MTFileIconProvider.java:49)		
		at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)		
		at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:118)		
		at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)		
		at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)		
		at com.intellij.ui.DeferredIconImpl.b(DeferredIconImpl.java:161)		
		at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)		
		at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:161)		
		at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)		
		at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)		
		at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)		
		at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)		
		at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)		
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)		
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)		
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)		
		at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)		
		at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)		
		at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:111)		
		at com.intellij.ui.DeferredIconImpl.a(DeferredIconImpl.java:160)		
		at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)		
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)		
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)		
		at java.lang.Thread.run(Thread.java:745)
```

**Comment by mallowigi** [comment]
thanks. publishing a fix right away

**Comment by mallowigi** [comment]
can we close this?

**Comment by IGassmann** [comment]
Yep, it does work now.

On Mon, Jun 5, 2017 at 11:23, Elior Boukhobza <notifications@github.com> wrote:
can we close this?
