### ISSUE TITLE
Update to 0.5.3.1 make theme crash

### ISSUE THREAD

**Issue by stefensuhat** [mallowigi/material-theme-jetbrains-eap#70]
```
Plugin 'com.chrisrm.idea.MaterialThemeUIFork' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'theme' of com/chrisrm/idea/MTLaf.<init> must not be null
    at com.chrisrm.idea.MTLaf.$$$reportNull$$$0(MTLaf.java)
    at com.chrisrm.idea.MTLaf.<init>(MTLaf.java)
    at com.chrisrm.idea.themes.MTThemeManager.activate(MTThemeManager.java:156)
    at com.chrisrm.idea.themes.MTThemeManager.activate(MTThemeManager.java:144)
    at com.chrisrm.idea.schemes.MTColorSchemeComponent.activateTheme(MTColorSchemeComponent.java:20)
    at com.chrisrm.idea.schemes.MTColorSchemeComponent.initComponent(MTColorSchemeComponent.java:13)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mallowigi** [comment]
Hmmm... were you using "remove theme" theme by chance?

**Comment by stefensuhat** [comment]
@mallowigi nope. My previous material theme version 0.4.4 working properly. After I update it become crash when restart the phpstorm.

Already tried install and reinstall the plugin still happen and it happen on non fork material theme too.

**Comment by mallowigi** [comment]
I mean, what theme were you using prior to updating?

**Comment by mallowigi** [comment]
like Default? Darker?

**Comment by stefensuhat** [comment]
I changed the color scheme to Dracula.

Look and feel using Darcula.

**Comment by mallowigi** [comment]
which ide do you use? And which OS?

**Comment by stefensuhat** [comment]
IDE: latest phpstorm.

OS: Windows 10

**Comment by mallowigi** [comment]
Ok can you please copy paste here the contents of the file located at

C:\Users\<username>\.PHPStorm2017.X\config\options\material_theme.xml ?

**Comment by stefensuhat** [comment]
```
<application>
  <component name="MaterialThemeConfig">
    <option name="selectedTheme" value="NONE" />
    <option name="highlightColor" value="80cbc4" />
    <option name="isBoldTabs" value="true" />
    <option name="wallpaper" value="https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-extended/master/src/main/resources/themes/wall.jpg,60,60,60,60" />
    <option name="wallpaperSet" value="false" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
great. Now change the value of "selectedTheme" from NONE to DEFAULT and it should work.

**Comment by stefensuhat** [comment]
@mallowigi still happen. and phpstorm automatically disable the plugin

**Comment by mallowigi** [comment]
wait. You must change it when the IDE is closed, right? also maybe just remove the whole option.

**Comment by stefensuhat** [comment]
my bad. I type "default" with lowercase. it should uppercase. now its working properly.  💃 

thanks

**Comment by mallowigi** [comment]
Thanks. The issue is because I removed the "NONE" option in the latest update, so it fails to load.

I don't want to readd it so I will leave this issue open for other people to do the same if they encounter the problem.

Sorry :)

**Comment by ssmithstone** [comment]
where would that file be located on os x ?

**Comment by mallowigi** [comment]
/home/Library/Preferences/.PHPStorm2017.X/config/options IIRC

**Comment by mallowigi** [comment]
and in Linux it's /home/<user>/.PHPStorm2017.X/config/options

**Comment by mallowigi** [comment]
and of course if it's not PHPStorm go to the relevant IDE's config folder

**Comment by ssmithstone** [comment]
im getting the following error 

null
java.lang.NullPointerException
	at com.chrisrm.idea.themes.MTLafComponent.lambda$setStatusBarBorders$3(MTLafComponent.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

running intellij on macOs , was working fine until the latest update

**Comment by mallowigi** [comment]
which ide?

**Comment by mallowigi** [comment]
Also please open a new issue, this is not related to the previous one

**Comment by mallowigi** [comment]
Ok with the latest hotfix the bug should not happen regardless of what theme was set previously.
